# Generated by Django 5.2.8 on 2025-11-17 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("base_cpv", models.IntegerField()),
                ("cpv_audience", models.IntegerField()),
                ("cpv_non_target", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Bonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bonus_type", models.CharField(max_length=100)),
                ("condition_type", models.CharField(max_length=100)),
                ("min_value", models.FloatField(default=0.0)),
                ("rate", models.FloatField()),
                ("description", models.CharField(max_length=255)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonuses",
                        to="api.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Surcharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surcharge_type", models.CharField(max_length=100)),
                ("condition_value", models.CharField(max_length=100)),
                ("rate", models.FloatField()),
                ("description", models.CharField(max_length=255)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surcharges",
                        to="api.channel",
                    ),
                ),
            ],
        ),
    ]
