# Generated by Django 5.0.7 on 2024-07-25 07:37
import csv
from django.db import migrations

def load_initial_data(apps, schema_editor):
    Channel = apps.get_model('api', 'Channel')
    Bonus = apps.get_model('api', 'Bonus')
    Surcharge = apps.get_model('api', 'Surcharge')

    # Load Channels
    with open('data/channels.csv', 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)  # Skip header
        for row in reader:
            Channel.objects.create(
                name=row[0],
                base_cpv=int(row[1]),
                cpv_audience=int(row[2]),
                cpv_non_target=int(row[3]),
            )

    # Load Bonuses
    with open('data/bonuses.csv', 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)  # Skip header
        for row in reader:
            channel = Channel.objects.get(name=row[0])
            Bonus.objects.create(
                channel=channel,
                bonus_type=row[1],
                condition_type=row[2],
                min_value=float(row[3]),
                rate=float(row[4]),
                description=row[5],
            )

    # Load Surcharges
    with open('data/surcharges.csv', 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)  # Skip header
        for row in reader:
            channel = Channel.objects.get(name=row[0])
            Surcharge.objects.create(
                channel=channel,
                surcharge_type=row[1],
                condition_value=row[2],
                rate=float(row[3]),
                description=row[4],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
